### ISSUE TITLE
Add to awesome-cakephp

### ISSUE THREAD

**Issue by dereuromark** [stefanvangastel/CakePHP-FeedbackIt#16]
Did you consider adding your plugin to the [awesome list](https://github.com/FriendsOfCake/awesome-cakephp/tree/cake2) ?

If so, is there a reason to keep your current license? Most (99%) CakePHP (plugin) code runs under the MIT license.
Not a big deal, just asking if there is a specific reason, and if MIT would also do.

Also, some basic test coverage (via travis) would be needed to ensure quality and prevent basic regressions.

**Comment by stefanvangastel** [comment]
Thanks Mark, will do that! Was planning some maintenance and updating anyway. Will keep you posted.

**Comment by dereuromark** [comment]
Cool
A 3.x version would also be awesome :)

**Comment by dereuromark** [comment]
PS: Is it MIT or GPL license? composer states MIT, but license file says otherwise.
I would recommend using the standard non copy left MIT here for both.
To fix that would be important as otherwise this is not usable as plugin for many people without violating copyright law.

**Comment by dereuromark** [comment]
I took the liberty of upgrading to 3.x and apply some improvements.
as soon as we figured out the license issue I can push it into a repository.

**Comment by stefanvangastel** [comment]
Awesome, if you have a PR ready, pls do change to MIT.

**Comment by dereuromark** [comment]
PR done.
