### ISSUE TITLE
Upgrade to 3.x

### ISSUE THREAD

**Issue by dereuromark** [stefanvangastel/CakePHP-FeedbackIt#18]
As promised I added a 3.x upgrade: https://github.com/dereuromark/cakephp-feedback

The current status is linked here for u:
https://github.com/stefanvangastel/CakePHP-FeedbackIt/wiki

Only afterwards I then also stumbled upon https://github.com/akkaweb/AKKA-CakePHP-Feedback-Plugin 
Similar, but yours is more awesome due to the screenshot part, of course. :)

**Comment by stefanvangastel** [comment]
Cool, if you could make a PR to merge your Cake 3 changes that would be awesome.

**Comment by amenk** [comment]
@dereuromark do you plan to make a PR?

**Comment by dereuromark** [comment]
I currently maintain the 3.x version. I can close for now.
